// <auto-generated />
using System;
using PeakSet.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace PeakSet.Infrastructure.Migrations
{
    [DbContext(typeof(PeakSetDbContext))]
    [Migration("20260820232705_SeedExerciseCatalog")]
    partial class SeedExerciseCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PeakSet.Domain.Entities.CompletedTrainingCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoutineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WeeksCompleted")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CompletedTrainingCycles");
                });

            modelBuilder.Entity("PeakSet.Domain.Entities.ExerciseCatalogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultLaterality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ExerciseCatalogEntries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ea29f7bd-478d-5a3d-a890-c7880b7abb5a"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Press de Banca"
                        },
                        new
                        {
                            Id = new Guid("27503eee-cabc-5b52-92ce-d0d21fe31c23"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Press de Banca Inclinado"
                        },
                        new
                        {
                            Id = new Guid("d13ad581-d222-5191-be04-73244bf4c367"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Press de Banca Declinado"
                        },
                        new
                        {
                            Id = new Guid("a13ba155-5060-5768-ba7d-a68963e20495"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Press con Mancuernas"
                        },
                        new
                        {
                            Id = new Guid("02f3f6fe-c951-5e2c-8193-f23688f501ce"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Press Inclinado con Mancuernas"
                        },
                        new
                        {
                            Id = new Guid("efeed315-dd0c-5f09-959b-b3f753baef29"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Press en Máquina"
                        },
                        new
                        {
                            Id = new Guid("2f447b3a-5051-56ec-82bf-cc078cdf385f"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Press Hammer Strength"
                        },
                        new
                        {
                            Id = new Guid("4e1b2f99-499a-5adc-8f10-d61653133ae9"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Chest Press en Máquina"
                        },
                        new
                        {
                            Id = new Guid("4e7caacc-c5f0-5edb-9297-ebf420c259ac"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Aperturas con Mancuernas"
                        },
                        new
                        {
                            Id = new Guid("0ea1c6ed-02cf-5dc9-bc68-e7345870b695"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Aperturas en Máquina"
                        },
                        new
                        {
                            Id = new Guid("6919cc95-f3f9-5337-a5e6-b4c23fcb8904"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Aperturas en Poleas"
                        },
                        new
                        {
                            Id = new Guid("7d58aad8-ac8c-5ef4-b750-85bf9fd1bdb5"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Peck Deck"
                        },
                        new
                        {
                            Id = new Guid("5f00b897-be5a-573b-a732-b07e8c585a73"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Press Militar con Barra"
                        },
                        new
                        {
                            Id = new Guid("66205a06-2a3a-51f9-95c2-09e64cd1db2d"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Press Militar con Mancuernas"
                        },
                        new
                        {
                            Id = new Guid("63b74f57-f1e4-5771-a7ee-dcbec1aa9bc0"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Press Militar en Máquina"
                        },
                        new
                        {
                            Id = new Guid("fc878cb8-32c7-5ee9-a59b-46ba1a3549bb"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Arnold Press"
                        },
                        new
                        {
                            Id = new Guid("0b56946a-da6c-5d3f-94e0-2ddc0d06d25c"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Push Press"
                        },
                        new
                        {
                            Id = new Guid("706b3c15-bedc-5e42-98e4-2398c751cdb5"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Elevaciones Laterales"
                        },
                        new
                        {
                            Id = new Guid("b707e25b-15da-5ffe-bda4-85a8bade2cdf"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Elevaciones Laterales en Máquina"
                        },
                        new
                        {
                            Id = new Guid("a1b02ab3-8208-54df-94bf-896ddee7d808"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Elevaciones Frontales"
                        },
                        new
                        {
                            Id = new Guid("a50a3fa5-7d82-5a9d-bb0f-add7b6a7d543"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Pájaros (Deltoide Posterior)"
                        },
                        new
                        {
                            Id = new Guid("b67e126d-9ecc-5826-95b9-78e90088ca77"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Reverse Peck Deck"
                        },
                        new
                        {
                            Id = new Guid("fa095d4c-f1a4-52f4-82aa-c33c9b6fa791"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Bodyweight",
                            Name = "Fondos en Paralelas"
                        },
                        new
                        {
                            Id = new Guid("283984eb-10a5-548d-a703-cf5123627106"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Fondos en Máquina Asistida"
                        },
                        new
                        {
                            Id = new Guid("631c1db1-d4b1-59cc-b0b9-192c7feb499c"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Bodyweight",
                            Name = "Fondos en Banco"
                        },
                        new
                        {
                            Id = new Guid("dae1feb4-2e05-5e34-bf90-4c19dfb83df6"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Bodyweight",
                            Name = "Flexiones"
                        },
                        new
                        {
                            Id = new Guid("0807d52a-bace-5734-b016-2658215b99fb"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Bodyweight",
                            Name = "Flexiones Diamante"
                        },
                        new
                        {
                            Id = new Guid("ea0c22ea-5576-5395-8e0d-e89240254d69"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Bodyweight",
                            Name = "Flexiones Declive"
                        },
                        new
                        {
                            Id = new Guid("40051f28-4773-57e7-96c9-477a2b8dc513"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Extensión de Tríceps en Polea"
                        },
                        new
                        {
                            Id = new Guid("1fbca1cc-fe5d-5a51-8859-d7249faf9a5e"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Extensión de Tríceps con Cuerda"
                        },
                        new
                        {
                            Id = new Guid("b7adebc1-0cc9-549d-a715-46ce91a86422"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Extensión de Tríceps en Máquina"
                        },
                        new
                        {
                            Id = new Guid("e53ed0c4-05c3-5c94-8714-669a82e98028"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Extensión Overhead con Mancuerna"
                        },
                        new
                        {
                            Id = new Guid("c5a5342d-6759-5c6a-a56a-4f3c0ecf62a8"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Tríceps Francés"
                        },
                        new
                        {
                            Id = new Guid("3b472797-55d5-5313-b923-1cd009fd3120"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Press Cerrado"
                        },
                        new
                        {
                            Id = new Guid("f41cee49-0fd7-5b91-93f1-04748bf18a7a"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Bodyweight",
                            Name = "Dominadas Pronadas"
                        },
                        new
                        {
                            Id = new Guid("d6ff9fab-9bf9-5e86-b4c4-a917594ac193"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Bodyweight",
                            Name = "Dominadas Supinas (Chin Up)"
                        },
                        new
                        {
                            Id = new Guid("eea84f69-4f14-5856-b36b-6828da6d2b75"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Bodyweight",
                            Name = "Dominadas Neutras"
                        },
                        new
                        {
                            Id = new Guid("3d3fa499-fa54-534f-9f97-9891de0b772a"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Dominadas en Máquina Asistida"
                        },
                        new
                        {
                            Id = new Guid("4b204d3a-4a3a-524a-b093-331644e5a200"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Jalón al Pecho"
                        },
                        new
                        {
                            Id = new Guid("4714d208-6042-544f-939d-c2bdd7851df4"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Jalón Agarre Cerrado"
                        },
                        new
                        {
                            Id = new Guid("0e73b905-0027-530d-b8dc-c1f2be0f0531"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Jalón Unilateral"
                        },
                        new
                        {
                            Id = new Guid("363df271-b263-597b-beff-e1659a38893e"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Remo con Barra"
                        },
                        new
                        {
                            Id = new Guid("8214e37d-3268-5a67-bdec-f82895fe5cdd"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Remo Pendlay"
                        },
                        new
                        {
                            Id = new Guid("9dda4b65-a421-582c-810f-810777014163"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Remo con Mancuerna"
                        },
                        new
                        {
                            Id = new Guid("a4c20eee-267d-5193-95f9-481a8176a6a3"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Remo en Polea Baja"
                        },
                        new
                        {
                            Id = new Guid("bb7ce2ef-1874-5477-9e60-d4606218c24f"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Remo en Máquina"
                        },
                        new
                        {
                            Id = new Guid("3fa770e1-b7d8-5879-b855-df34da9b2426"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Remo Hammer Strength"
                        },
                        new
                        {
                            Id = new Guid("99a331ae-c76b-58e5-b977-8f0cd1254130"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Remo T-Bar"
                        },
                        new
                        {
                            Id = new Guid("85d63843-52ef-5397-a62f-41258782959a"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Remo Alto en Polea"
                        },
                        new
                        {
                            Id = new Guid("8c7c2375-0b50-52ea-ace7-a43fc7e15bd8"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Pullover en Máquina"
                        },
                        new
                        {
                            Id = new Guid("558a1dca-f170-5483-8f05-8d0dc0556119"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Pullover en Polea"
                        },
                        new
                        {
                            Id = new Guid("4f902f28-8351-5ed1-afe1-95ad20efda04"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Face Pull"
                        },
                        new
                        {
                            Id = new Guid("7a267408-d662-51ea-9ecf-d14768e06b4d"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Curl de Bíceps con Barra"
                        },
                        new
                        {
                            Id = new Guid("2a48b934-4c06-53c0-afc3-bccf579a0e81"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Curl de Bíceps con Mancuernas"
                        },
                        new
                        {
                            Id = new Guid("08224b0a-cc35-5572-8758-3966c60d8cf1"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Curl Martillo"
                        },
                        new
                        {
                            Id = new Guid("60c68901-081b-5e80-b28f-f329441fe182"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Curl en Máquina"
                        },
                        new
                        {
                            Id = new Guid("df9703da-5326-5082-8f01-14a83a3a55b4"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Curl Predicador"
                        },
                        new
                        {
                            Id = new Guid("8cdbab6c-e87c-54b1-97dc-1f9ef1c20c77"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Curl Scott"
                        },
                        new
                        {
                            Id = new Guid("5808b076-a2da-5848-8a93-d316337d1161"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Curl en Polea"
                        },
                        new
                        {
                            Id = new Guid("cd587f34-0702-5d03-b2bd-408801853d25"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Sentadilla Trasera"
                        },
                        new
                        {
                            Id = new Guid("a7126405-a988-57b5-a3ab-eda55a4699bd"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Sentadilla Frontal"
                        },
                        new
                        {
                            Id = new Guid("1bc014d9-1ba1-5591-8baa-53694b2da198"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Sentadilla Goblet"
                        },
                        new
                        {
                            Id = new Guid("d3f3c117-fc77-5c8a-9b6d-d38bc60e96ac"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Sentadilla Hack"
                        },
                        new
                        {
                            Id = new Guid("8ceac6d6-aca0-5d63-be61-114fa5915841"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Sentadilla Hack Inversa"
                        },
                        new
                        {
                            Id = new Guid("b7d4cbe5-3034-55f0-8f7d-053b51951005"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Sentadilla en Máquina"
                        },
                        new
                        {
                            Id = new Guid("3eb3361a-b306-5e7a-8613-47fd4783297a"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Sentadilla Smith"
                        },
                        new
                        {
                            Id = new Guid("0d1b0f28-f46a-5a83-ae17-466988e0c456"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Prensa de Piernas 45°"
                        },
                        new
                        {
                            Id = new Guid("bbf4fd8c-a3d0-5bc0-8055-4def27d5ab41"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Prensa de Piernas Horizontal"
                        },
                        new
                        {
                            Id = new Guid("4c726686-8113-5c21-a78e-b33a740d9079"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Prensa de Piernas Unilateral"
                        },
                        new
                        {
                            Id = new Guid("47f27e7d-2e12-561b-a545-aad1aad886d8"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Peso Muerto Convencional"
                        },
                        new
                        {
                            Id = new Guid("bcbf5ee0-774b-51fa-b81c-8ef37db04d9b"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Peso Muerto Sumo"
                        },
                        new
                        {
                            Id = new Guid("aa27d0c5-0d71-5157-9bab-e476234d5b09"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Peso Muerto Rumano"
                        },
                        new
                        {
                            Id = new Guid("690b6019-86f1-5c51-a573-6077ead0a1b9"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Peso Muerto en Máquina"
                        },
                        new
                        {
                            Id = new Guid("28c73b58-9fe7-5b4e-9075-a1fcdcf74586"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Hip Thrust con Barra"
                        },
                        new
                        {
                            Id = new Guid("2a0f772d-506b-570c-a645-7629b689aca7"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Hip Thrust en Máquina"
                        },
                        new
                        {
                            Id = new Guid("adff15a8-cfb8-57ae-9b5f-d1581f961a1e"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Zancadas Caminando"
                        },
                        new
                        {
                            Id = new Guid("755b18a8-f5a1-55dd-8ba9-baacb1e649ec"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Zancadas Estáticas"
                        },
                        new
                        {
                            Id = new Guid("5a464ab5-5ab7-51a3-a2a7-e5cc16b78580"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Zancadas Reversas"
                        },
                        new
                        {
                            Id = new Guid("eed953ff-6b64-5e6a-b0ad-d5024576af29"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Zancadas en Smith"
                        },
                        new
                        {
                            Id = new Guid("b8254256-1c4d-5c6e-a71c-4f26b6986282"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Extensiones de Cuádriceps"
                        },
                        new
                        {
                            Id = new Guid("9dda5755-d509-50b7-8eb4-bf8e64920077"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Curl Femoral Acostado"
                        },
                        new
                        {
                            Id = new Guid("90519e77-6d7e-56c3-b73a-a314a383144a"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Curl Femoral Sentado"
                        },
                        new
                        {
                            Id = new Guid("3e01e0bd-63c7-5792-bfd1-380df349b01b"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Curl Femoral de Pie"
                        },
                        new
                        {
                            Id = new Guid("459e5221-44b3-537b-bbf5-c35d3c8638e5"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Aductores en Máquina"
                        },
                        new
                        {
                            Id = new Guid("c1695b98-4900-5526-a776-f1f71873b06a"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Abductores en Máquina"
                        },
                        new
                        {
                            Id = new Guid("97332d61-2584-5ed0-9cef-066c23d26221"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Elevación de Gemelos de Pie"
                        },
                        new
                        {
                            Id = new Guid("f34a088e-dbc4-58a2-83b9-e28e53f4ac30"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Elevación de Gemelos Sentado"
                        },
                        new
                        {
                            Id = new Guid("d4287efd-6457-52a9-a561-06a80698333d"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Gemelos en Prensa"
                        },
                        new
                        {
                            Id = new Guid("9a5ae25d-8135-56e7-9f1c-fa013198fb3b"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Bodyweight",
                            Name = "Crunch Abdominal"
                        },
                        new
                        {
                            Id = new Guid("83b43adc-dcdd-5a2f-9b87-06a9e40ccb31"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Crunch en Máquina"
                        },
                        new
                        {
                            Id = new Guid("4c9a7b16-23b9-5ecf-a501-998005c5a0fa"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Standard",
                            Name = "Crunch en Polea"
                        },
                        new
                        {
                            Id = new Guid("eb272348-6711-581e-8ff5-627bb4acd6fa"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Bodyweight",
                            Name = "Crunch Declinado"
                        },
                        new
                        {
                            Id = new Guid("263dd739-a740-5656-85c2-e017c98cbf16"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Time",
                            Name = "Plancha Abdominal"
                        },
                        new
                        {
                            Id = new Guid("62e2a5b6-9564-5c7d-84cf-4b171decca62"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Time",
                            Name = "Plancha Lateral"
                        },
                        new
                        {
                            Id = new Guid("ebbbdad5-4d7a-5ea7-929c-b4b38dd0f510"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Time",
                            Name = "Plancha con Peso"
                        },
                        new
                        {
                            Id = new Guid("52a4d1da-d696-5c5f-89b2-752a125e623c"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Bodyweight",
                            Name = "Elevaciones de Piernas"
                        },
                        new
                        {
                            Id = new Guid("6c32ed4a-2fda-5cec-aa5e-05b25807be04"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Bodyweight",
                            Name = "Elevaciones de Piernas Colgado"
                        },
                        new
                        {
                            Id = new Guid("01154a22-56a2-5fa4-963f-69329aabc964"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Bodyweight",
                            Name = "Ab Wheel"
                        },
                        new
                        {
                            Id = new Guid("eebbe44c-0279-5bdf-8dc8-e9d8c8522352"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Time",
                            Name = "Saltar Cuerda"
                        },
                        new
                        {
                            Id = new Guid("6d79b895-e8b1-500e-9dba-a75f24871949"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Bodyweight",
                            Name = "Burpees"
                        },
                        new
                        {
                            Id = new Guid("7526326f-bac5-5ffd-a0b1-dc17aae06df8"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Bodyweight",
                            Name = "Jump Squats"
                        },
                        new
                        {
                            Id = new Guid("009a3bcd-daf6-5197-ab4c-86e5dc7814e1"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Time",
                            Name = "Caminadora"
                        },
                        new
                        {
                            Id = new Guid("b175cd6e-2fb8-5991-9f11-4940ad28bf91"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Time",
                            Name = "Bicicleta Estática"
                        },
                        new
                        {
                            Id = new Guid("ed18781e-5a2b-52fc-af43-f229537b25f8"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Time",
                            Name = "Bicicleta Reclinada"
                        },
                        new
                        {
                            Id = new Guid("e9674430-dd28-5667-ba9f-09d92907c6a9"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Time",
                            Name = "Elíptica"
                        },
                        new
                        {
                            Id = new Guid("a902f83f-29a7-5500-9449-48db5adf8086"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Time",
                            Name = "Escaladora"
                        },
                        new
                        {
                            Id = new Guid("6cc59bb5-cc15-57b3-ad5c-f2145de3c829"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Time",
                            Name = "Remo Ergómetro"
                        },
                        new
                        {
                            Id = new Guid("d30189d9-0b3e-5168-9466-c71ecd1dd0fa"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Time",
                            Name = "Assault Bike"
                        },
                        new
                        {
                            Id = new Guid("6d452d26-1055-5b3e-90a0-fa8782b35d66"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Time",
                            Name = "Wall Sit"
                        },
                        new
                        {
                            Id = new Guid("5928c72b-1667-5592-a48c-102b17a72fba"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Time",
                            Name = "Dead Hang"
                        },
                        new
                        {
                            Id = new Guid("a2f5ab27-11dc-5b37-ac87-04552ca9ec66"),
                            DefaultLaterality = "Bilateral",
                            ExerciseType = "Time",
                            Name = "Farmer Walk"
                        });
                });

            modelBuilder.Entity("PeakSet.Domain.Entities.ExerciseNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("NoteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ExerciseName")
                        .IsUnique();

                    b.ToTable("ExerciseNotes");
                });

            modelBuilder.Entity("PeakSet.Domain.Entities.Routine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Routines");
                });

            modelBuilder.Entity("PeakSet.Domain.Entities.SessionExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Laterality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("WorkoutSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("SessionExercise");
                });

            modelBuilder.Entity("PeakSet.Domain.Entities.TrainingCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentWeek")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoutineId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalWeeks")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoutineId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("TrainingCycles", t =>
                        {
                            t.HasCheckConstraint("CK_TrainingCycles_CurrentWeek_Range", "\"CurrentWeek\" >= 1 AND \"CurrentWeek\" <= \"TotalWeeks\"");
                        });
                });

            modelBuilder.Entity("PeakSet.Domain.Entities.UserExercisePreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Laterality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ExerciseName")
                        .IsUnique();

                    b.ToTable("UserExercisePreferences");
                });

            modelBuilder.Entity("PeakSet.Domain.Entities.UserSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TimerPrepSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("TimerRestSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("TimerSets")
                        .HasColumnType("integer");

                    b.Property<int>("TimerWorkSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("PeakSet.Domain.Entities.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RoutineId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoutineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("WorkoutDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoutineId");

                    b.HasIndex("UserId", "WorkoutDate");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("PeakSet.Domain.Entities.WorkoutExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Laterality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PrStatus")
                        .HasColumnType("text");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutExercise");
                });

            modelBuilder.Entity("PeakSet.Domain.Entities.WorkoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("RoutineId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoutineId");

                    b.ToTable("WorkoutSession");
                });

            modelBuilder.Entity("PeakSet.Domain.Entities.WorkoutSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.Property<Guid>("WorkoutExerciseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutExerciseId");

                    b.ToTable("WorkoutSet", t =>
                        {
                            t.HasCheckConstraint("CK_WorkoutSets_Reps_NonNegative", "\"Reps\" >= 0");

                            t.HasCheckConstraint("CK_WorkoutSets_SetNumber_Positive", "\"SetNumber\" > 0");

                            t.HasCheckConstraint("CK_WorkoutSets_Weight_NonNegative", "\"Weight\" >= 0");
                        });
                });

            modelBuilder.Entity("PeakSet.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PeakSet.Domain.Entities.CompletedTrainingCycle", b =>
                {
                    b.HasOne("PeakSet.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PeakSet.Domain.Entities.ExerciseNote", b =>
                {
                    b.HasOne("PeakSet.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PeakSet.Domain.Entities.Routine", b =>
                {
                    b.HasOne("PeakSet.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PeakSet.Domain.Entities.SessionExercise", b =>
                {
                    b.HasOne("PeakSet.Domain.Entities.WorkoutSession", null)
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PeakSet.Domain.Entities.TrainingCycle", b =>
                {
                    b.HasOne("PeakSet.Domain.Entities.Routine", null)
                        .WithMany()
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeakSet.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PeakSet.Domain.Entities.UserExercisePreference", b =>
                {
                    b.HasOne("PeakSet.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PeakSet.Domain.Entities.UserSettings", b =>
                {
                    b.HasOne("PeakSet.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PeakSet.Domain.Entities.Workout", b =>
                {
                    b.HasOne("PeakSet.Domain.Entities.Routine", null)
                        .WithMany()
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PeakSet.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PeakSet.Domain.Entities.WorkoutExercise", b =>
                {
                    b.HasOne("PeakSet.Domain.Entities.Workout", null)
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PeakSet.Domain.Entities.WorkoutSession", b =>
                {
                    b.HasOne("PeakSet.Domain.Entities.Routine", null)
                        .WithMany("Sessions")
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PeakSet.Domain.Entities.WorkoutSet", b =>
                {
                    b.HasOne("PeakSet.Domain.Entities.WorkoutExercise", null)
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PeakSet.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PeakSet.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeakSet.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PeakSet.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PeakSet.Domain.Entities.Routine", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("PeakSet.Domain.Entities.Workout", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("PeakSet.Domain.Entities.WorkoutExercise", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("PeakSet.Domain.Entities.WorkoutSession", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
